common/models/Questions.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "questions".
 *
 * @property int $id
 * @property int $creator_id
 * @property string $science
 * @property string $question
 * @property string $answer_one
 * @property string $answer_two
 * @property string $answer_three
 * @property string $answer_four
 * @property int $status
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $deleted_at
 */
class Questions extends BaseTimestampedModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'questions';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['creator_id', 'science', 'question', 'answer_one', 'answer_two', 'answer_three', 'answer_four'], 'required'],
            [['creator_id', 'status', 'created_at', 'updated_at', 'deleted_at'], 'integer'],
            [['science', 'question', 'answer_one', 'answer_two', 'answer_three', 'answer_four'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'creator_id' => Yii::t('app', 'Creator ID'),
            'science' => Yii::t('app', 'Science'),
            'question' => Yii::t('app', 'Question'),
            'answer_one' => Yii::t('app', 'Answer One'),
            'answer_two' => Yii::t('app', 'Answer Two'),
            'answer_three' => Yii::t('app', 'Answer Three'),
            'answer_four' => Yii::t('app', 'Answer Four'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'deleted_at' => Yii::t('app', 'Deleted At'),
        ];
    }
}

backend/controllers/QuestionsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Questions;
use common\models\search\QuestionsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * QuestionsController implements the CRUD actions for Questions model.
 */
class QuestionsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Questions models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new QuestionsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Questions model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Questions model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Questions();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionImport()
    {
        return $this->redirect(['import']);
    }

    /**
     * Updates an existing Questions model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Questions model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Questions model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Questions the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Questions::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/questions/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Questions */
/* @var $form yii\widgets\ActiveForm */
?>
<script type="text/javascript">
    $('.my').change(function() {
        if ($(this).val() != '')
            $(this).prev().text('Выбрано файлов: ' + $(this)[0].files.length);
        else
            $(this).closest('.box-form').children('.label').text('Exceldan yuklash');
});
</script>
<style type="text/css">
    .my {
        width: 0.1px;
        height: 0.1px;
        opacity: 0;
        overflow: hidden;
        position: absolute;
        z-index: -1;
    }
    .label {
        width: 180px;
        height: 50px;
        border-radius: 4px;
        text-align: center;
        cursor: pointer;
        display: block;
        font: 14px/50px Tahoma;
        transition: all 0.18s ease-in-out;
        border: 1px solid #333;
        color: #333;
    }
    
    .label:hover {
        color: white;
        background: #00ff00;
    }
</style>

<div class="container box-form">
    <h4>Exceldan yuklash (*.xlsx)</h4>
    <form action="<?= Url::to(['questions/import']) ?>" method="post">
        <div>
            <label for="myfile" class="label btn btn-info">Faylni tanlang</label>
        </div>
        <div>
            <input type="file" class="my" id="myfile" name="myfile">
        </div>
        <br>
        <button class="btn btn-success"> Yuklash </button>
    </form>
    <br>
<div>
<div class="questions-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'science')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'question')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'answer_one')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'answer_two')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'answer_three')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'answer_four')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/questions/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\QuestionsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="questions-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'creator_id') ?>

    <?= $form->field($model, 'science') ?>

    <?= $form->field($model, 'question') ?>

    <?= $form->field($model, 'answer_one') ?>

    <?php // echo $form->field($model, 'answer_two') ?>

    <?php // echo $form->field($model, 'answer_three') ?>

    <?php // echo $form->field($model, 'answer_four') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'deleted_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/questions/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Questions */

$this->title = Yii::t('app', 'Create Questions');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Questions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="questions-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/questions/import.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\search\QuestionsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="questions-index">

    <h1><?= Html::encode($this->title) ?></h1>

	<?php
	if (isset($_FILES['file'])) {
		
		require_once __DIR__ . '/simplexlsx.class.php';
		
		if ( $xlsx = SimpleXLSX::parse( $_FILES['file']['tmp_name'] ) ) {

			echo '<h2>Parsing Result</h2>';
			echo '<table border="1" cellpadding="3" style="border-collapse: collapse">';

			list( $cols, ) = $xlsx->dimension();

			foreach ( $xlsx->rows() as $k => $r ) {
				//		if ($k == 0) continue; // skip first row
				echo '<tr>';
				for ( $i = 0; $i < $cols; $i ++ ) {
					echo '<td>' . ( ( isset( $r[ $i ] ) ) ? $r[ $i ] : '&nbsp;' ) . '</td>';
				}
				echo '</tr>';
			}
			echo '</table>';
		} else {
			echo SimpleXLSX::parse_error();
		}
	}
?>
</div>

backend/views/questions/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use common\models\constants\CommonStatus;
use common\models\constants\UserRole;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\QuestionsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Questions');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="questions-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create Questions'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            // 'creator_id',
            [
                'attribute' => 'creator_id',
                'value' => function ($model) {
                    return $model->creator->full_name;
                },
                'filter' => Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'creator_id',
                    'data' => ArrayHelper::map(\common\models\User::findActive()->all(), 'id', 'full_name'),
                    'theme' => Select2::THEME_BOOTSTRAP,
                    'options' => [
                        'placeholder' => Yii::t('yii', 'Tanlang...'),
                        'value' => $searchModel->creator_id
                    ],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]),
            ],
            // 'science',
            [
                'attribute' => 'science',
                'value' => function ($model) {
                    return $model->science;
                },
                // 'filter' => Select2::widget([
                //     'model' => $searchModel,
                //     'attribute' => 'creator_id',
                //     'data' => ArrayHelper::map(\common\models\Science::findActive()->all(), 'id', 'science_name'),
                //     'theme' => Select2::THEME_BOOTSTRAP,
                //     'options' => [
                //         'placeholder' => Yii::t('yii', 'Tanlang...'),
                //         'value' => $searchModel->creator_id
                //     ],
                //     'pluginOptions' => [
                //         'allowClear' => true
                //     ],
                // ]),
            ],
            'question',
            'answer_one',
            //'answer_two',
            //'answer_three',
            //'answer_four',
            // 'status',
            [
                'attribute' => 'status',
                'value' => function($model){
                    return CommonStatus::getString($model->status);
                },
                'filter' => CommonStatus::getArray()
            ],
            //'created_at',
            //'updated_at',
            //'deleted_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

backend/views/questions/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Questions */

$this->title = Yii::t('app', 'Update Questions: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Questions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="questions-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/questions/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Questions */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Questions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="questions-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            // 'creator_id',
            [
                'attribute' => 'creator_id',
                'value' => $model->creator->full_name,
            ],
            'science',
            'question',
            'answer_one',
            'answer_two',
            'answer_three',
            'answer_four',
            // 'status',
            [
                'attribute' => 'status',
                'value' => common\models\constants\CommonStatus::getString($model->status),
            ],
            'created_at:datetime',
            'updated_at:datetime',
            'deleted_at:datetime',
        ],
    ]) ?>

</div>